# Generated by Django 5.2.8 on 2025-11-20 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('modo_preparo', models.TextField()),
                ('tempo_preparo', models.IntegerField()),
                ('image', models.URLField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(related_name='receitas', through='receitas.IngredientReceita', to='receitas.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientreceita',
            name='receita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.post'),
        ),
    ]
