# Generated by Django 5.2.8 on 2025-11-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='ingredientreceita',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientreceita',
            name='receita',
        ),
        migrations.AlterField(
            model_name='post',
            name='tempo_preparo',
            field=models.IntegerField(default=0, help_text='tempo em minutos'),
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientReceita',
        ),
    ]
