# Generated by Django 5.2.8 on 2025-11-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DOC', 'Doce'), ('SAL', 'Salgado'), ('VEG', 'Vegetariano'), ('VEGANO', 'Vegano'), ('BEB', 'Bebida'), ('NAT', 'Natal')], null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receitas', models.ManyToManyField(to='receitas.post')),
            ],
        ),
    ]
