# Generated by Django 5.2.8 on 2025-11-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='autor',
        ),
        migrations.AlterField(
            model_name='category',
            name='categoria',
            field=models.CharField(blank=True, choices=[('DOC', 'Doce'), ('SAL', 'Salgado'), ('VEG', 'Vegetariano'), ('VEGANO', 'Vegano'), ('BEB', 'Bebida'), ('NAT', 'Natal')], max_length=200, null=True),
        ),
    ]
